name: Video-Summarization
channels:
  - defaults
dependencies:
  - attrs=20.3.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - ca-certificates=2021.4.13=hecd8cb5_1
  - certifi=2020.12.5=py36hecd8cb5_0
  - icu=58.2=h0a44026_3
  - importlib-metadata=3.10.0=py36hecd8cb5_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.2.0=hecd8cb5_564
  - jpeg=9b=he5867d9_2
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36h9ed2024_0
  - mkl_fft=1.3.0=py36ha059aab_0
  - mkl_random=1.1.1=py36h959d312_0
  - more-itertools=8.7.0=pyhd3eb1b0_0
  - ncurses=6.2=h0a44026_1
  - numpy-base=1.19.2=py36hcfb5961_0
  - openssl=1.1.1k=h9ed2024_0
  - packaging=20.9=pyhd3eb1b0_0
  - pip=21.0.1=py36hecd8cb5_0
  - pluggy=0.13.1=py36hecd8cb5_0
  - py=1.10.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pytest=6.2.3=py36hecd8cb5_2
  - python=3.6.13=h88f2d9e_0
  - qt=5.9.7=h468cd18_1
  - readline=8.1=h9ed2024_0
  - scipy=1.5.2=py36h912ce22_0
  - setuptools=52.0.0=py36hecd8cb5_0
  - six=1.15.0=py36hecd8cb5_0
  - sqlite=3.35.4=hce871da_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.2=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - chardet==4.0.0
    - decorator==4.4.2
    - ffmpeg-python==0.2.0
    - future==0.18.2
    - idna==2.10
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.3
    - moviepy==1.0.3
    - numpy==1.19.5
    - opencv-contrib-python==4.5.1.48
    - pillow==8.2.0
    - proglog==0.1.9
    - requests==2.25.1
    - tqdm==4.60.0
    - urllib3==1.26.4
